# Generated by Django 4.2.8 on 2023-12-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(default='book.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', null=True, upload_to=''),
        ),
    ]
